# Generated by Django 3.1.7 on 2021-03-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Wordhunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=25)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('roundtype', models.CharField(choices=[('prelims', 'Prelims'), ('final', 'Finals')], max_length=8)),
                ('images', models.ManyToManyField(to='wordhunt.Images')),
            ],
            options={
                'verbose_name': 'Wordhunt',
            },
        ),
    ]
