# Generated by Django 3.1.7 on 2021-03-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordhunt', '0002_stud_res_wordhunt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stud_res_wordhunt',
            options={'verbose_name': 'Student Result WordHunt'},
        ),
    ]
