# Generated by Django 3.1.7 on 2021-03-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordhunt', '0004_auto_20210307_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordhunt',
            options={'verbose_name': 'Question'},
        ),
    ]
