# Generated by Django 3.1.7 on 2021-03-07 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='user',
            new_name='student',
        ),
        migrations.AddField(
            model_name='logo',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
