# Generated by Django 3.1.7 on 2021-03-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0003_poster_roundtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='roundtype',
            field=models.CharField(choices=[('prelims', 'Prelims'), ('final', 'Finals')], max_length=8),
        ),
    ]
