# Generated by Django 3.1.7 on 2021-03-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0004_auto_20210307_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(upload_to='Logo'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='poster',
            field=models.ImageField(upload_to='Poster'),
        ),
    ]
