# Generated by Django 3.1.7 on 2021-03-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0005_auto_20210307_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='description',
            field=models.TextField(blank=True, max_length=430, null=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='roundtype',
            field=models.CharField(blank=True, choices=[('prelims', 'Prelims'), ('final', 'Finals')], max_length=8, null=True),
        ),
    ]
