# Generated by Django 3.1.7 on 2021-03-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0006_auto_20210307_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='description',
            field=models.TextField(max_length=430),
        ),
        migrations.AlterField(
            model_name='logo',
            name='roundtype',
            field=models.CharField(choices=[('prelims', 'Prelims'), ('final', 'Finals')], max_length=8),
        ),
    ]
