# Generated by Django 3.1.7 on 2021-03-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0007_auto_20210307_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='status',
        ),
        migrations.AddField(
            model_name='logo',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
