# Generated by Django 3.1.7 on 2021-03-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0008_auto_20210309_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
