# Generated by Django 3.1.7 on 2021-03-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0010_auto_20210309_0709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo Result'},
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': 'Poster Result'},
        ),
    ]
