# Generated by Django 3.1.7 on 2021-03-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='test_timings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('word hunt', 'Word Hunt'), ('code treasure', 'Code Treasure'), ('logo design', 'Logo Design'), ('poster design', 'Poster Design')], max_length=20)),
                ('round_type', models.CharField(choices=[('preliminary', 'preliminary'), ('final', 'final')], max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='prelim_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('word hunt', 'Word Hunt'), ('code treasure', 'Code Treasure'), ('logo design', 'Logo Design'), ('poster design', 'Poster Design')], max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('test_status', models.CharField(choices=[('started', 'started'), ('finished', 'finished'), ('seated', 'seated'), ('not started', 'not started')], max_length=20)),
                ('attended', models.BooleanField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='final_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('word hunt', 'Word Hunt'), ('code treasure', 'Code Treasure'), ('logo design', 'Logo Design'), ('poster design', 'Poster Design')], max_length=20)),
                ('placed', models.CharField(choices=[('selected', 'selected'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('test_status', models.CharField(choices=[('started', 'started'), ('finished', 'finished'), ('seated', 'seated'), ('not started', 'not started')], max_length=20)),
                ('attended', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
