# Generated by Django 3.1.7 on 2021-03-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20210307_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='bonafide',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='id_proof',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
