# Generated by Django 3.1.7 on 2021-03-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20210307_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='bonafide',
            field=models.FileField(upload_to='Student_bonafide'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='id_proof',
            field=models.ImageField(upload_to='Student_id'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='profile_pic',
            field=models.ImageField(upload_to='Student_pic'),
        ),
    ]
