# Generated by Django 3.1.7 on 2021-03-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20210307_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'verbose_name': 'Student'},
        ),
    ]
