# Generated by Django 3.1.7 on 2021-03-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20210307_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='address',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='college_address',
            field=models.TextField(max_length=150),
        ),
    ]
