# Generated by Django 3.1.7 on 2021-03-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_auto_20210307_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='id_proof',
            field=models.ImageField(help_text="Don't have Id Card, then get signature from your college", upload_to='Student_id'),
        ),
    ]
