# Generated by Django 3.1.7 on 2021-03-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20210307_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='is_codetreasure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='is_geekspeak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='is_impreza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='is_ransack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='is_webdodger',
            field=models.BooleanField(default=False),
        ),
    ]
