# Generated by Django 3.1.7 on 2021-03-09 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_auto_20210309_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_timings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('wordhunt', 'Word Hunt'), ('codetreasure', 'Code Treasure'), ('logo', 'Logo Design'), ('poster', 'Poster Design'), ('ppt', 'Paper Presentation')], max_length=20)),
                ('round_type', models.CharField(choices=[('preliminary', 'preliminary'), ('final', 'final')], max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='prelim_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('wordhunt', 'Word Hunt'), ('codetreasure', 'Code Treasure'), ('logo', 'Logo Design'), ('poster', 'Poster Design'), ('ppt', 'Paper Presentation')], max_length=20)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('test_status', models.CharField(choices=[('started', 'started'), ('finished', 'finished'), ('cheated', 'cheated'), ('not_started', 'not started')], max_length=20)),
                ('attended', models.BooleanField(default=False)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='final_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('wordhunt', 'Word Hunt'), ('codetreasure', 'Code Treasure'), ('logo', 'Logo Design'), ('poster', 'Poster Design'), ('ppt', 'Paper Presentation')], max_length=20)),
                ('placed', models.CharField(choices=[('selected', 'selected'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=20)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('test_status', models.CharField(choices=[('started', 'started'), ('finished', 'finished'), ('seated', 'seated'), ('not_started', 'not started')], max_length=20)),
                ('attended', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
