# Generated by Django 3.1.7 on 2021-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_auto_20210309_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_test',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='final_test',
            name='event',
            field=models.CharField(choices=[('wordhunt', 'Word Hunt'), ('codetreasure', 'Code Treasure'), ('logo', 'Logo Design'), ('poster', 'Poster Design'), ('ppt', 'Paper Presentation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='final_test',
            name='placed',
            field=models.CharField(choices=[('selected', 'selected'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), ('notselected', 'Not Selected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='final_test',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prelim_test',
            name='event',
            field=models.CharField(choices=[('wordhunt', 'Word Hunt'), ('codetreasure', 'Code Treasure'), ('logo', 'Logo Design'), ('poster', 'Poster Design'), ('ppt', 'Paper Presentation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prelim_test',
            name='test_status',
            field=models.CharField(choices=[('started', 'started'), ('finished', 'finished'), ('cheated', 'cheated'), ('not_started', 'not started')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test_timings',
            name='event',
            field=models.CharField(choices=[('wordhunt', 'Word Hunt'), ('codetreasure', 'Code Treasure'), ('logo', 'Logo Design'), ('poster', 'Poster Design'), ('ppt', 'Paper Presentation')], max_length=20),
        ),
    ]
