# Generated by Django 3.1.7 on 2021-03-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_auto_20210309_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_test',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='final_test',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final_test',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final_test',
            name='test_status',
            field=models.CharField(choices=[('started', 'started'), ('finished', 'finished'), ('seated', 'seated'), ('not_started', 'not started')], max_length=20),
        ),
    ]
