# Generated by Django 3.1.7 on 2021-03-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_final_test_prelim_test_test_timings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='final_test',
            options={'verbose_name': 'Finals Test'},
        ),
        migrations.AlterModelOptions(
            name='prelim_test',
            options={'verbose_name': 'Prelims Test'},
        ),
        migrations.AlterModelOptions(
            name='test_timings',
            options={'verbose_name': 'Test Timing'},
        ),
        migrations.AlterField(
            model_name='final_test',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
