# Generated by Django 3.1.7 on 2021-03-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_auto_20210309_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_test',
            name='test_status',
            field=models.CharField(choices=[('started', 'started'), ('finished', 'finished'), ('cheated', 'cheated'), ('not_started', 'not started')], max_length=20),
        ),
    ]
