# Generated by Django 3.1.7 on 2021-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_auto_20210309_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelim_test',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prelim_test',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
