# Generated by Django 3.1.7 on 2021-03-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210306_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question',
            new_name='question_model',
        ),
    ]
