# Generated by Django 3.1.7 on 2021-03-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210306_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_code_shuffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='final_code_shuffle/')),
            ],
        ),
        migrations.CreateModel(
            name='final_code_shuffle_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ManyToManyField(to='questions.final_code_shuffle')),
            ],
        ),
    ]
