# Generated by Django 3.1.7 on 2021-03-07 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_final_code_shuffle_final_code_shuffle_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_code_binary_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='final_code_spot_error_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ImageField(upload_to='final_code_spot_error/')),
            ],
        ),
        migrations.CreateModel(
            name='final_answer_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=50)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('final_code_binary_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.final_code_binary_question')),
                ('final_code_shuffle_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.final_code_shuffle_relation')),
                ('final_code_spot_error_questio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.final_code_spot_error_question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
