# Generated by Django 3.1.7 on 2021-03-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_final_answer_relation_final_code_binary_question_final_code_spot_error_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_answer_relation',
            name='user_answer',
            field=models.CharField(max_length=250),
        ),
    ]
