# Generated by Django 3.1.7 on 2021-03-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210307_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_answer_relation',
            name='user_answer',
            field=models.TextField(),
        ),
    ]
