# Generated by Django 3.1.7 on 2021-03-07 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='question_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option_A', models.CharField(max_length=30)),
                ('option_B', models.CharField(max_length=30)),
                ('option_C', models.CharField(max_length=30)),
                ('option_D', models.CharField(max_length=30)),
                ('correct_option', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stud_Res_CodeTreasure_Prelm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetreasure.question_model')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
