# Generated by Django 3.1.7 on 2021-03-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codetreasure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_model',
            options={'verbose_name': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='stud_res_codetreasure_prelm',
            options={'verbose_name': 'Student Result Prelim'},
        ),
    ]
