# Generated by Django 3.1.7 on 2021-03-07 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codetreasure', '0002_auto_20210307_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_code_binary_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Binary Hunter Question',
            },
        ),
        migrations.CreateModel(
            name='final_code_shuffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='final_code_shuffle/')),
            ],
            options={
                'verbose_name': 'Code Shuffle Image',
            },
        ),
        migrations.CreateModel(
            name='final_code_spot_error_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='final_code_spot_error/')),
            ],
            options={
                'verbose_name': 'Spot Error Images',
            },
        ),
        migrations.CreateModel(
            name='final_code_spot_error_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ManyToManyField(to='codetreasure.final_code_spot_error_image')),
            ],
            options={
                'verbose_name': 'Spot Error Answer',
            },
        ),
        migrations.CreateModel(
            name='final_code_shuffle_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ManyToManyField(to='codetreasure.final_code_shuffle')),
            ],
            options={
                'verbose_name': 'Code Shuffle Questions',
            },
        ),
        migrations.CreateModel(
            name='final_answer_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('final_code_binary_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codetreasure.final_code_binary_question')),
                ('final_code_shuffle_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codetreasure.final_code_shuffle_relation')),
                ('final_code_spot_error_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codetreasure.final_code_spot_error_question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Result Final',
            },
        ),
    ]
