# Generated by Django 3.1.7 on 2021-03-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codetreasure', '0003_final_answer_relation_final_code_binary_question_final_code_shuffle_final_code_shuffle_relation_fina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='final_code_spot_error_image',
            options={'verbose_name': 'Spot Error Image'},
        ),
    ]
