# Generated by Django 3.1.7 on 2021-03-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codetreasure', '0004_auto_20210308_0533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='final_code_spot_error_question',
            options={'verbose_name': 'Spot Error Question'},
        ),
    ]
