# Generated by Django 3.1.7 on 2021-03-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codetreasure', '0005_auto_20210308_0539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='final_code_shuffle_relation',
            options={'verbose_name': 'Code Shuffle Question'},
        ),
        migrations.AlterModelOptions(
            name='question_model',
            options={'verbose_name': 'Prelims Aptitude Question'},
        ),
    ]
