# Generated by Django 3.1.7 on 2021-03-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetreasure', '0006_auto_20210308_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_model',
            name='question',
            field=models.CharField(max_length=450),
        ),
    ]
