# Generated by Django 3.1.7 on 2021-03-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetreasure', '0008_auto_20210308_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_code_binary_question',
            name='ques_no',
            field=models.CharField(default='Binaryhunt', max_length=80),
        ),
        migrations.AddField(
            model_name='final_code_shuffle_relation',
            name='ques_no',
            field=models.CharField(default='Codeshuffle', max_length=80),
        ),
        migrations.AddField(
            model_name='final_code_spot_error_question',
            name='ques_no',
            field=models.CharField(default='SpotError', max_length=80),
        ),
    ]
