# Generated by Django 3.1.7 on 2021-03-09 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codetreasure', '0009_auto_20210309_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_codetreasureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundtype', models.CharField(choices=[('prelims', 'Prelims'), ('final', 'Finals')], max_length=8)),
                ('score', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
