# Generated by Django 3.1.7 on 2021-03-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codetreasure', '0010_score_codetreasuremodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score_codetreasuremodel',
            options={'verbose_name': 'Score'},
        ),
    ]
